### ISSUE TITLE
More Description Issues: Tantares Size 1 Basic & Non-Basic Service Compartments

### ISSUE THREAD

**Issue by MorganPLU** [Tantares/Tantares#101]
Hiya Tantares!

Feels mean to bring another of these up, but both of the tanks listed show in their description "Monopropellant? In This Economy?"
When they now use LF/Ox mixture as of the Soyuz-derived engines and RCS thrusters.

Thanks,
Morgan :)

**Comment by Tantares** [comment]
Thanks for finding this, fixed now.
