### ISSUE TITLE
VA Heat property

### ISSUE THREAD

**Issue by Anachro19** [Tantares/Tantares#103]
VA Capsule cannot withstand the reentry of a 2.5~2.7x Kerbin due to heat property issue of Alnair heat shields.

**Comment by Tantares** [comment]
Will investigate for coming release. Thanks

**Comment by Anachro19** [comment]
Thank you！I can feel that the next release for FGB/TKS would be better than ever.etc：I havn't tested but I doubt that the LK -700 heat shield is sharing the same problem in the case that they are really similar.发自 Android 版 Yahoo 邮箱 
 
  2021 年 4 月 20 日周二上午 1:56，Leo ***@***.***> 写道：   


Will investigate for coming release. Thanks

**Comment by AstroWell** [comment]
i've noticed VA heatshield size 2 have only 300 Ablator, compared to stock heatshield wich have 800 Ablator.
Stock Heatshield have also 	PhysicsSignificance = 0 but i don't think that related.

VA heatshield size 1p5 have also 300 Ablator, 500 for the Stock 1p5 heatshield with also PhysicsSignificance = 0

**Comment by AstroWell** [comment]
Beale let me know if you want a pull request to fix that

**Comment by Anachro19** [comment]
Sure, there is already a request on GitHub.

发送自 Windows 10 版邮件应用

发件人: Stéphane Colombain
发送时间: 2021年6月7日 23:42
收件人: Tantares/Tantares
抄送: Anachro19; Author
主题: Re: [Tantares/Tantares] VA Heat property (#103)

Beale let me know if you want a pull request to fix that

**Comment by Tantares** [comment]
Thanks for details, updated heatshield to 500 ab
further testing to do

**Comment by Delliardo** [comment]
If you cheat the VA/TKS and Proton to orbit, the VA doesn't heat up.  If you do a normal launch, VA heats up and explodes during re-entry

I'm in JNSQ, 150x150km orbit at 45 degrees inclination.  I de-orbit until Mechjeb landing guidance says 4.4g.  And yes, I have cheat orbited the whole proton stack to see if it's a part interaction with the fairings or the Launch Escape Tower, but it might be KSP's buggy heat system.
