### ISSUE TITLE
No highlights

### ISSUE THREAD

**Issue by joey-lg** [Tantares/Tantares#104]
I can't seem to detach or right click on tantares parts (solar panels, engines, some spacecraft parts). Also, they do not appear in staging. 
If you want the ksp.log, here it is.

[KSP.txt](https://github.com/Tantares/Tantares/files/6488586/KSP.txt)

**Comment by Tantares** [comment]
Need to use KSP 1.11
Bug with vanilla game, nothing I can do.

**Comment by joey-lg** [comment]
ok. Thanks for the info.
