### ISSUE TITLE
problems with the CKAN

### ISSUE THREAD

**Issue by ry4kas** [Tantares/Tantares#107]
what is the problem, I downloaded the program everything as always done, launched and the program can not find the repository modifications, in the settings of the site ctrl c ctrl v in the browser and there is no such site, I found I do not remember where the address of the repository and added it to the CKAN and so it does not work, what is the problem? 
![Screenshot_4](https://user-images.githubusercontent.com/85797746/121780843-35f89480-cbb3-11eb-891d-3b688be6d4e5.png)

unable to connect to remote server

**Comment by Tantares** [comment]
Please report this to CKAN developer, I have no control over this.
