### ISSUE TITLE
Lunakhod Rover Body 'Chassis' only

### ISSUE THREAD

**Issue by cdodders** [Tantares/Tantares#110]
Request for a variant of the Lunakhod rover body with the lower part and suspension only, to be able to use as a chassis for other rover deisgns, ,such as the one shown here (done with clipping).
![screenshot2478](https://user-images.githubusercontent.com/30770566/128073965-a5a69a63-188a-45c9-9c6a-acb68981b179.png)
![screenshot2479](https://user-images.githubusercontent.com/30770566/128073978-a741d2d3-968f-4866-abcc-55ea9da4e17d.png)

**Comment by Tantares** [comment]
Interesting idea, please can you open issue on the TantaresSP repo?
