### ISSUE TITLE
Localization keys missing

### ISSUE THREAD

**Issue by HorusAK** [Tantares/Tantares#117]
Localization is missing for new solar array part.

https://github.com/Tantares/Tantares/blob/db96d332503993f08ebd22ecda1efba37a7e7e4c/GameData/Tantares/parts/any_solar/mir/_eridani_solar_srf_3_2B.cfg#L27

https://github.com/Tantares/Tantares/blob/db96d332503993f08ebd22ecda1efba37a7e7e4c/GameData/Tantares/parts/any_solar/mir/_eridani_solar_srf_3_2B.cfg#L29

https://github.com/Tantares/Tantares/blob/db96d332503993f08ebd22ecda1efba37a7e7e4c/GameData/Tantares/parts/any_solar/mir/_eridani_solar_srf_3_2B.cfg#L31

**Comment by Tantares** [comment]
Thankyou, resolved.
