### ISSUE TITLE
BG (and/or IR) Lyappa arm

### ISSUE THREAD

**Issue by JacobB094** [Tantares/Tantares#120]
Now that KSP has robotics and Tantares is back in dev, a really nice addition to Mir would be robotics, specifically the Lyappa arm. This is an uncomplicated device, consisting of one hinge and one rotator. Its end effector grapples to one of the two fixtures on the core module, the hinge lifts it out, and the arm then rotates to move the module to another port.

**Comment by Tantares** [comment]
Hey I'm really sorry, but the actual modules for robotics are not included in the game, I don't want Tantares to depend on the paid DLC. Hope that makes sense.
