### ISSUE TITLE
Correct name for T-RYD 1x6 Photovoltaic Panels

### ISSUE THREAD

**Issue by MichielBijl** [Tantares/Tantares#3]
The 1x4 panels for the modern Soyuz craft is [incorrectly named as Beale pointed out](http://forum.kerbalspaceprogram.com/index.php?/topic/73686-122-tantares-stockalike-soyuz-and-lk-1005022017/&page=536#comment-2974382) in in the topic.

Just creating this so you don’t forget ;).

**Comment by Tantares** [comment]
Fixed.
