### ISSUE TITLE
Stock part switch broken in 1.6

### ISSUE THREAD

**Issue by swavkulinski** [Tantares/Tantares#42]
Hi,

this is just a heads up. Replication is hard to get.

I am using: 
1.5.1 Tantares
KSP 1.6 

Everything seems to work apart from **variant switch** which **sometimes** bugs out part context menu (right-click)
Attempt to right-click on a Tantares part with variants e.g. (T-2CR dobbelboks Crew Module) causes a menu to show in the top right corner and its contents is replaced by a stack of Variant sliders. After that I can't open any menus on other parts. This looks to me like KSP problem not the mod itself, however **stock parts are not affected**. 

I will try to post the screenshot when I am lucky to get the bug again. After game restart everything works fine.

**Comment by swavkulinski** [comment]
Can't replicate anymore. My theory is this was MM issue with cache. I was using old Tantares before then replaced with new one. Feel free to close it.

**Comment by DeltaDizzy** [comment]
> My theory is this was MM issue with cache.

In the interest of making sure people are informed I will tell you the actual cause of this. There was a stock bug with PartDatabase in 1.6.0 which was intensified by MM. MM was modified to actually fix the bug with version 4.0.0, and Squad fixed it on their end in KSP 1.6.1.

> Feel free to close it.

There should be a button for you to do it.
