### ISSUE TITLE
T-OM1B Oribital Module Name used twice

### ISSUE THREAD

**Issue by PadroneSF** [Tantares/Tantares#43]
There are two related pairs of parts involved.  

T-OM1 and T-OM1B are nearly identical parts that are round, T-OM1 has a T-ML1 sized flat spot on both ends, the T--OM1B has one T-ML1 size spot and one T-KR1 sized spot.

T-OM1B (not the same as above) and T-SZ1 are cylinder shaped.  T-OM1B has two flat T-ML1 spots, and T-SZ1 has a T-ML1 spot and a T-KR1 spot.

Having two different parts with the same name is confusing.

I suggest renaming second T-OM1B to something like "T-SZ0 Habitation Section". This would group them together in a similar manner to the first two mentioned.

I believe that the actual part name file is "_Soyuz_Orbital_2.cfg"

I also believe two corrections are needed in that CFG file.  Right now they duplicate the round T-OM1b.  If there aren't individual entries for this part, at least the Title and Description should be:

title        = #LOC_Tantares_Tantares_Orbital_2
description  = #LOC_Tantares_Tantares_Orbital_2_Description

**Comment by Tantares** [comment]
Fixed.
