### ISSUE TITLE
Octans Androgynous Size 0.5 Docking Port B don't dock or undock

### ISSUE THREAD

**Issue by AstroWell** [Tantares/Tantares#69]
octans_androgynous_docking_port_s0p5_2 = Octans Androgynous Size 0.5 Docking Port B

Don't dock or Undock, the config file look fine, i suspect a wrong axis for the docking transform, or a missing transform.

If used with a Port A variant to force undock using the A variant, i have a nullref after undock

![screenshot0](https://user-images.githubusercontent.com/30159391/81820549-0d761500-9531-11ea-82ab-b6a710b68cc9.jpg)

**Comment by Tantares** [comment]
B port was missing transform. Fixed, many thanks!
