### ISSUE TITLE
Green Variant for Vega/Salyut parts are broken

### ISSUE THREAD

**Issue by AstroWell** [Tantares/Tantares#70]
_tantares_vega_crew_s1_1_1 = Vega 12-A1 "Luftlås" Airlock Compartment
tantares_vega_crew_s1_1_2 = Vega 12-A2 "Luftlås" Airlock Compartment
tantares_vega_crew_s1_2_1 = Vega 12-B1 "Utgang" Airlock Compartment
tantares_vega_crew_s2_1_1 = Vega 25-A1 "Halehvelv" Tail Compartment_
**Those parts are supposed to have a green variant but just show the grey texture.**

_tantares_vega_crew_s1p5_1_1 = Vega 18-A1 "Nervesystemet" Command Module_
**This part is also supposed to have a green variant according to the variant label, but switch to white**

Config look fine, i think the texture was just never exported with the green color layer for those parts. Vega 18-A1 "Nervesystemet" Command Module probably just need a white label instead of green.

**Comment by Tantares** [comment]
Resolved.
