### ISSUE TITLE
#LOC title for many parts are broken (show #LOC instead of the title)

### ISSUE THREAD

**Issue by AstroWell** [Tantares/Tantares#71]
Many parts don't show the title but only the #LOC
Just a typo error from what i've see:

**#LOC_tantares_octans_les_s0_1 = Octans Launch Escape System**
Config call  #LOC_rantares_octans_les_s0_1

**#LOC_tantares_hadar_fuselage_s1 = Hadar Size 1 Fuselage**
Config Call #LOC_tantares_hadar_fuselage_s1_1

**#LOC_tantares_lepus_ladder_srf_1 = Lepus CL-A1 Folding ladder**
Config Call #LOC_tantares_ladder_srf_1

**#LOC_tantares_lepus_ladder_srf_2 = Lepus CL-A2 Folding Ladder**
Config Call #LOC_tantares_ladder_srf_2

**Comment by Tantares** [comment]
typos in LOCs fixed.
