### ISSUE TITLE
DXT3 format not supported (Castor)

### ISSUE THREAD

**Issue by AstroWell** [Tantares/Tantares#72]
[ERR 14:11:02.266] DDS: DXT3(8x8, MipMap=True) - DXT3 format is NOT supported. Use DXT5

[WRN 14:11:02.282] Texture load error in 'C:\Jeux\Kerbal Space Program\Kerbal Space Program 1.9.1\GameData\Tantares\Parts\ANY\CONTROL_CORE\OLD\Texture_Castor_General_1.dds'

I suppose that a Deprecated part ? don't remember.
Maybe we can delete those old Deprecated part for a final update ? (Look like They are still loaded in game ? Could be great to finally remove them)

**Comment by AstroWell** [comment]
[ERR 14:11:02.726] DDS: DXT3(8x8, MipMap=True) - DXT3 format is NOT supported. Use DXT5
[WRN 14:11:02.726] Texture load error in 'C:\Jeux\Kerbal Space Program\Kerbal Space Program 1.9.1\GameData\Tantares\Parts\LK\DEPRECATED\Texture_Libra_General_1.dds'

[ERR 14:11:02.748] DDS: DXT3(8x8, MipMap=True) - DXT3 format is NOT supported. Use DXT5
[WRN 14:11:02.748] Texture load error in 'C:\Jeux\Kerbal Space Program\Kerbal Space Program 1.9.1\GameData\Tantares\Parts\LK\DEPRECATED\Texture_Libra_General_1_NRM.dds'

**Comment by Tantares** [comment]
Deprecated parts removed.
