### ISSUE TITLE
Missing texture errors (Deprecated parts ?)

### ISSUE THREAD

**Issue by AstroWell** [Tantares/Tantares#74]
[LOG 14:11:18.799] Load(Model): Tantares/Parts/ANY/CONTROL_CORE/OLD/Castor_Control_1_N
[ERR 14:11:18.800] Texture 'Tantares/Parts/ANY/CONTROL_CORE/OLD/Texture_Castor_General_1' not found!

[LOG 14:11:18.823] Load(Model): Tantares/Parts/ANY/CONTROL_CORE/OLD/Castor_Control_1_O
[ERR 14:11:18.824] Texture 'Tantares/Parts/ANY/CONTROL_CORE/OLD/Texture_Castor_General_1' not found!

[LOG 14:11:18.866] Load(Model): Tantares/Parts/ANY/CONTROL_CORE/OLD/Castor_Control_1_P
[ERR 14:11:18.868] Texture 'Tantares/Parts/ANY/CONTROL_CORE/OLD/Texture_Castor_General_1' not found!

[LOG 14:11:22.702] Load(Model): Tantares/Parts/LK/DEPRECATED/LK_Antenna_1
[ERR 14:11:22.702] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1' not found!

[LOG 14:11:22.726] Load(Model): Tantares/Parts/LK/DEPRECATED/LK_Antenna_2
[ERR 14:11:22.727] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1' not found!

[LOG 14:11:22.749] Load(Model): Tantares/Parts/LK/DEPRECATED/LK_Crew_1
[ERR 14:11:22.752] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1' not found!

[ERR 14:11:22.752] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1_NRM' not found!

[LOG 14:11:22.783] Load(Model): Tantares/Parts/LK/DEPRECATED/LK_Engine_1
[ERR 14:11:22.784] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1' not found!

[ERR 14:11:22.784] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1_NRM' not found!

[LOG 14:11:22.807] Load(Model): Tantares/Parts/LK/DEPRECATED/LK_Ladder_1
[ERR 14:11:22.808] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1' not found!

[LOG 14:11:22.832] Load(Model): Tantares/Parts/LK/DEPRECATED/LK_Leg_1
[ERR 14:11:22.833] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1' not found!

[LOG 14:11:22.855] Load(Model): Tantares/Parts/LK/DEPRECATED/LK_LFO_1
[ERR 14:11:22.857] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1' not found!

[ERR 14:11:22.858] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1_NRM' not found!

[LOG 14:11:22.890] Load(Model): Tantares/Parts/LK/DEPRECATED/LK_Nesting_1
[ERR 14:11:22.891] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1' not found!

[LOG 14:11:22.913] Load(Model): Tantares/Parts/LK/DEPRECATED/LK_RCS_1
[ERR 14:11:22.915] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1' not found!

[ERR 14:11:22.915] Texture 'Tantares/Parts/LK/DEPRECATED/Texture_Libra_General_1_NRM' not found!

[LOG 14:11:24.317] Load(Model): Tantares/Parts/MIR-37K/KVANT_Lab_1
[ERR 14:11:24.336] Texture 'Tantares/Parts/MIR-37K/Texture_Emissive' not found!

[LOG 14:11:24.353] Load(Model): Tantares/Parts/MIR-37K/KVANT_Lab_2
[ERR 14:11:24.371] Texture 'Tantares/Parts/MIR-37K/Texture_Emissive' not found!

[LOG 14:11:26.536] Load(Model): Tantares/Parts/SOYUZ/DEPRECATED/Soyuz_Port_A
[ERR 14:11:26.538] Texture 'Tantares/Parts/SOYUZ/DEPRECATED/Tantares_Crew_A_psd' not found!

[LOG 14:11:26.556] Load(Model): Tantares/Parts/SOYUZ/DEPRECATED/Soyuz_Port_B
[ERR 14:11:26.557] Texture 'Tantares/Parts/SOYUZ/DEPRECATED/Tantares_Crew_A_psd' not found!

**Comment by Tantares** [comment]
All deprecated parts removed.
