### ISSUE TITLE
Typo error on the variant theme of octans_androgynous_docking_port_s0p5_1

### ISSUE THREAD

**Issue by AstroWell** [Tantares/Tantares#77]
[LOG 14:11:46.831] PartLoader: Compiling Part 'Tantares/Parts/ANY/SOYUZ_ANDROGYNOUS_DOCKING_PORT/_octans_androgynous_docking_port_s0p5_1/octans_androgynous_docking_port_s0p5_1'
[ERR 14:11:46.941] Unable to find theme named:'tantares_greenn' in GameDB

Need to be probably 'tantares_green'

**Comment by AstroWell** [comment]
according to other parts 'tantares_greenn' sound correct, don't know why this theme is not loaded.
_octans_androgynous_docking_port_s0p5_2 load fine with the same theme.
I suggest to copy past the theme from this part

**Comment by Tantares** [comment]
Correct "greenn" to "green"
