### ISSUE TITLE
fx for decoupler missing

### ISSUE THREAD

**Issue by AstroWell** [Tantares/Tantares#78]
I now that a personnal choice, but i take the list of the parts if you decide to fix thos errors

Tantares/Parts/ANY/SOYUZ_PERISCOPE/_octans_periscope_srf_1/octans_periscope_srf_1
Tantares/Parts/LK/_libra_structure_s1_1/libra_structure_s1_1
Tantares/Parts/LK-1/_Auriga_DrogueParachute_1/Auriga_DrogueParachute_1

**Comment by AstroWell** [comment]
Tantares/Parts/LK-1/_Auriga_DrogueParachute_1/Auriga_DrogueParachute_1

**Comment by AstroWell** [comment]
Tantares/Parts/LK-1/_Auriga_Parachute_1/Auriga_Parachute_1
Tantares/Parts/LK-700/_aquarius_drogue_parachute_s0_1/aquarius_drogue_parachute_s0_1
Tantares/Parts/LK-700/_aquarius_parachute_s0p5_1/aquarius_parachute_s0p5_1
Tantares/Parts/LOK/_virgo_crew_s1_1/virgo_crew_s1_1

**Comment by AstroWell** [comment]
Tantares/Parts/POLYUS/_rotanev_aeroshell_s2_s1p5_1/rotanev_aeroshell_s2_s1p5_1

(4 null ref also for this parts, don't know if linked to the fx missing

**Comment by Tantares** [comment]
missing FX reinstate.
