### ISSUE TITLE
Duplicate name for solar panels

### ISSUE THREAD

**Issue by MichielBijl** [Tantares/Tantares#9]
Tantares_SolarStandard_1 and Tantares_SolarStandard_2 both have the name "T-RY2 1x4 Photovoltaic Panels".

Same for Tantares_SolarBasic_*

```
Part name						In-game name
Tantares_SolarBasic_1_L					T-RYD 1x6L Photovoltaic Panels
Tantares_SolarBasic_1_R					T-RYD 1x6R Photovoltaic Panels
Tantares_SolarBasic_2_L					T-RYD 1x6L Photovoltaic Panels
Tantares_SolarBasic_2_R					T-RYD 1x6R Photovoltaic Panels
```

**Comment by Tantares** [comment]
Well caught,

Basically currently to show they are absolutely identical parts in all but orientation.

Ripe for changing?

**Comment by MichielBijl** [comment]
For Tantares_SolarStandard_1 & 2 it would be enough to add L/R to the name me thinks.

Are all the Tantares_SolarBasic_*_L parts identical too?

**Comment by Tantares** [comment]
SolarStandard should be mirror image, currently no L & R variants.
Yes, this is the case - they are identical.
