### ISSUE TITLE
Hadar Crew Capsules

### ISSUE THREAD

**Issue by sick13** [Tantares/Tantares#93]
Ok the two "Crew" capsules seemingly are the same but their mass is not the same as far as i noticed

one has 0.45 mass the other 0.75
and slightly stronger Reaction wheels

just a thing you might consider looking into, or this might be intended

the files in Question are

 Tantares/GameData/Tantares/parts/PIRS/_hadar_crew_s1_1.cfg 

 Tantares/GameData/Tantares/parts/PIRS/_hadar_crew_s1_2.cfg

**Comment by Tantares** [comment]
Additional issue:
"

> You may be aware of this already but I couldn't find any mention of it in the thread. There appears to be a subtle typo in the configs for the Hadar Airlock Compartments A and B (parts/PIRS/_hadar_crew_s1_1.cfg and _hadar_crew_s1_2.cfg). The Minimum Crew to Operate is specified using "minimumcrew = 1" rather than "minimumCrew = 1". Apparently this value is case-sensitive, as both parts show up in-game as unmanned rather than requiring a pilot. Capitalising the "c" fixes the issue. 

"
