### ISSUE TITLE
LOC_tantares_vega_crew_s1p5_1_1 has no hatch

### ISSUE THREAD

**Issue by leoric** [Tantares/Tantares#95]
version 12.1, game version 1.8.9

Readable module name "Vega 18-A1 "Nervesystemet" Command Module"
Noticed when it was spawned as a capsule for rescue mission. No hatch, no docking capabilities = can't extract astronaut = death.

**Comment by Tantares** [comment]
This is a stock game mechanic out of my control. 
Treat this as an extra challenge, you will have to collect it in a cargo bay, or grab it.
