### ISSUE TITLE
Inconsistency in Virgo Monopropellant Tanks

### ISSUE THREAD

**Issue by hemeac** [Tantares/Tantares#97]
There are four Virgo Size 1 Monopropellant Tanks virgo_fuel_tank_s1_1 and _2 as well as virgo_radiator_fuel_tank_s1_1 and _2 which have Monopropellant Tank in the title, but are given Liquid Fuel and Oxidizer in their configurations.

**Comment by Tantares** [comment]
Thanks, to fix.

**Comment by Tantares** [comment]
Thanks! Corrected naming.
