### ISSUE TITLE
Rana Localization Descriptions

### ISSUE THREAD

**Issue by hemeac** [Tantares/Tantares#98]
A couple localization tags have an additional "s" in description so they are not matching the tag in the original config file:

Edit: The asterisks were added by me to try and make them bold to make it easier for you to see, that didn't work as intended...

// SOFORA

        #LOC_tantares_rana_control_srf_1 = Rana SRF-A "Datakasse" Control Block
        **#LOC_tantares_rana_control_srf_1_descriptions** = Refurbished from an old server, this control block might be small, but it's got a pedigree.
        #LOC_tantares_rana_control_srf_1_tags = mir zvezda sofora eridani rana

        #LOC_tantares_rana_mount_srf_1 = Rana Structural Mount
        **#LOC_tantares_rana_mount_srf_1_descriptions** = A small box on which things are mounted. Made from recycled snack drums.
        #LOC_tantares_rana_mount_srf_1_tags = mir zvezda sofora eridani rana

        #LOC_tantares_rana_truss_srf_1 = Rana Structural Truss A
        **#LOC_tantares_rana_truss_srf_1_descriptions** = A rigid structural truss - designed to be deployed during EVA, but that's not a rule.
        #LOC_tantares_rana_truss_srf_1_tags = mir zvezda sofora eridani rana

        #LOC_tantares_rana_truss_srf_2 = Rana Structural Truss B
        **#LOC_tantares_rana_truss_srf_2_descriptions** = A rigid structural truss - designed to be deployed during EVA, but that's not a rule.
        #LOC_tantares_rana_truss_srf_2_tags = mir zvezda sofora eridani rana

**Comment by Tantares** [comment]
Thanks!
Fixed.
